"""fix_updated_at_default

Revision ID: d740838dc51f
Revises: 
Create Date: 2026-04-06 22:31:32.575482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd740838dc51f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companys',
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_inn', sa.String(), nullable=False),
    sa.Column('company_type', sa.Enum('CUSTOMER', 'CARRIER', 'SUPPLIER', name='companytype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_inn'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('pallettypes',
    sa.Column('pallet_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pallet_type')
    )
    op.create_table('drivers',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('driver_phone_number', sa.String(), nullable=False),
    sa.Column('driver_licence_document', sa.String(), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['companys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_licence_document')
    )
    op.create_table('locations',
    sa.Column('full_address', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('phone_num', sa.String(), nullable=False),
    sa.Column('telegram', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CUSTOMER_MANAGER', 'CARRIER_MANAGER', 'SUPPLIER_MANAGER', name='usertype'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_num')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_number', sa.String(), nullable=False),
    sa.Column('vehicle_model', sa.String(), nullable=False),
    sa.Column('vehicle_capacity_tons', sa.Integer(), nullable=False),
    sa.Column('vehicle_capacity_euro_pallets', sa.Integer(), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['companys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_number')
    )
    op.create_table('trades',
    sa.Column('cargo_info', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('pallets', sa.Integer(), nullable=False),
    sa.Column('desired_pick_up_date', sa.Date(), nullable=False),
    sa.Column('desired_pick_up_time', sa.Time(), nullable=False),
    sa.Column('desired_delivery_date', sa.Date(), nullable=False),
    sa.Column('desired_delivery_time', sa.Time(), nullable=False),
    sa.Column('bidding_ends_at', sa.DateTime(), nullable=False),
    sa.Column('bidding_starts_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'BIDDING', 'SHIPPING', 'COMPLETED', 'CANCELLED', name='tradestatus'), nullable=False),
    sa.Column('initial_price', sa.Integer(), nullable=True),
    sa.Column('pallettype_id', sa.UUID(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('pickup_location_id', sa.UUID(), nullable=True),
    sa.Column('delivery_location_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['companys.id'], ),
    sa.ForeignKeyConstraint(['delivery_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['pallettype_id'], ['pallettypes.id'], ),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['companys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.UUID(), nullable=False),
    sa.Column('bid_creator_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bid_creator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['carrier_id'], ['companys.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('winnershipmentdetails',
    sa.Column('won_bid_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('files_urls', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['won_bid_id'], ['bids.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('won_bid_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('winnershipmentdetails')
    op.drop_table('bids')
    op.drop_table('trades')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('locations')
    op.drop_table('drivers')
    op.drop_table('pallettypes')
    op.drop_table('companys')
    # ### end Alembic commands ###
